/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label_trem1;
    QLabel *label_trilho1;
    QLabel *label_trilho2;
    QLabel *label_trilho3;
    QLabel *label_trilho4;
    QLabel *label_trilho3_5;
    QLabel *label_trilho1_2;
    QLabel *label_trilho2_2;
    QLabel *label_trem2;
    QSlider *vel_trem1;
    QSlider *vel_trem2;
    QSlider *vel_trem3;
    QSlider *vel_trem5;
    QSlider *vel_trem4;
    QLabel *label_trilho3_4;
    QLabel *label_trilho2_3;
    QLabel *label_trilho1_3;
    QLabel *label_trilho2_4;
    QLabel *label_trilho3_6;
    QLabel *label_trilho3_7;
    QLabel *label_trilho4_4;
    QLabel *label_trilho2_5;
    QLabel *label_trem3;
    QLabel *label_trem4;
    QLabel *label_trem5;
    QLabel *legend1;
    QLabel *legend2;
    QLabel *legend3;
    QLabel *legend4;
    QLabel *legend5;
    QLabel *label_trilho4_6;
    QLabel *ponto_critico_1;
    QLabel *ponto_critico_2;
    QLabel *ponto_critico_3;
    QLabel *ponto_critico_4;
    QLabel *ponto_critico_6;
    QLabel *ponto_critico_5;
    QLabel *ponto_critico_7;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1068, 529);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(46, 52, 54, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(69, 78, 81, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(57, 65, 67, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(23, 26, 27, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(30, 34, 36, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        MainWindow->setPalette(palette);
        MainWindow->setToolButtonStyle(Qt::ToolButtonIconOnly);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label_trem1 = new QLabel(centralWidget);
        label_trem1->setObjectName(QStringLiteral("label_trem1"));
        label_trem1->setGeometry(QRect(60, 30, 21, 17));
        label_trem1->setStyleSheet(QStringLiteral("QLabel { background: blue}"));
        label_trem1->setFrameShape(QFrame::NoFrame);
        label_trem1->setFrameShadow(QFrame::Plain);
        label_trem1->setLineWidth(1);
        label_trem1->setScaledContents(false);
        label_trilho1 = new QLabel(centralWidget);
        label_trilho1->setObjectName(QStringLiteral("label_trilho1"));
        label_trilho1->setGeometry(QRect(80, 30, 250, 17));
        label_trilho1->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho2 = new QLabel(centralWidget);
        label_trilho2->setObjectName(QStringLiteral("label_trilho2"));
        label_trilho2->setGeometry(QRect(80, 150, 250, 17));
        label_trilho2->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho3 = new QLabel(centralWidget);
        label_trilho3->setObjectName(QStringLiteral("label_trilho3"));
        label_trilho3->setGeometry(QRect(330, 30, 21, 137));
        label_trilho3->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho4 = new QLabel(centralWidget);
        label_trilho4->setObjectName(QStringLiteral("label_trilho4"));
        label_trilho4->setGeometry(QRect(60, 30, 21, 137));
        QPalette palette1;
        QBrush brush8(QColor(128, 128, 128, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        label_trilho4->setPalette(palette1);
        label_trilho4->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho3_5 = new QLabel(centralWidget);
        label_trilho3_5->setObjectName(QStringLiteral("label_trilho3_5"));
        label_trilho3_5->setGeometry(QRect(600, 30, 21, 137));
        label_trilho3_5->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho1_2 = new QLabel(centralWidget);
        label_trilho1_2->setObjectName(QStringLiteral("label_trilho1_2"));
        label_trilho1_2->setGeometry(QRect(350, 30, 250, 17));
        label_trilho1_2->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho2_2 = new QLabel(centralWidget);
        label_trilho2_2->setObjectName(QStringLiteral("label_trilho2_2"));
        label_trilho2_2->setGeometry(QRect(350, 150, 250, 17));
        label_trilho2_2->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trem2 = new QLabel(centralWidget);
        label_trem2->setObjectName(QStringLiteral("label_trem2"));
        label_trem2->setGeometry(QRect(330, 30, 21, 17));
        label_trem2->setStyleSheet(QStringLiteral("QLabel { background: green}"));
        vel_trem1 = new QSlider(centralWidget);
        vel_trem1->setObjectName(QStringLiteral("vel_trem1"));
        vel_trem1->setGeometry(QRect(100, 360, 160, 16));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush9(QColor(32, 74, 135, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush9);
        QBrush brush10(QColor(48, 111, 203, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush10);
        QBrush brush11(QColor(40, 92, 169, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        QBrush brush12(QColor(16, 37, 67, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(21, 49, 90, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush);
        QBrush brush14(QColor(143, 164, 195, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        QBrush brush15(QColor(145, 141, 126, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush15);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        vel_trem1->setPalette(palette2);
        vel_trem1->setStyleSheet(QStringLiteral("QLabel { background: pink}"));
        vel_trem1->setMaximum(200);
        vel_trem1->setValue(0);
        vel_trem1->setOrientation(Qt::Horizontal);
        vel_trem2 = new QSlider(centralWidget);
        vel_trem2->setObjectName(QStringLiteral("vel_trem2"));
        vel_trem2->setGeometry(QRect(100, 380, 160, 16));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush16(QColor(78, 154, 6, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush16);
        QBrush brush17(QColor(117, 231, 9, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush17);
        QBrush brush18(QColor(97, 192, 7, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush18);
        QBrush brush19(QColor(39, 77, 3, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush19);
        QBrush brush20(QColor(52, 103, 4, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush20);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Highlight, brush);
        QBrush brush21(QColor(166, 204, 130, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush21);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush17);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush18);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush19);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush20);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush19);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush17);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush18);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush19);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush20);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush19);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush19);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Highlight, brush15);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush16);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        vel_trem2->setPalette(palette3);
        vel_trem2->setMaximum(200);
        vel_trem2->setOrientation(Qt::Horizontal);
        vel_trem3 = new QSlider(centralWidget);
        vel_trem3->setObjectName(QStringLiteral("vel_trem3"));
        vel_trem3->setGeometry(QRect(100, 400, 160, 16));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush22(QColor(245, 121, 0, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush22);
        QBrush brush23(QColor(255, 183, 112, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush23);
        QBrush brush24(QColor(250, 152, 56, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush24);
        QBrush brush25(QColor(122, 60, 0, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush25);
        QBrush brush26(QColor(163, 80, 0, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush26);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush22);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Highlight, brush);
        QBrush brush27(QColor(250, 188, 127, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush27);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush22);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush23);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush24);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush25);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush26);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush22);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush27);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush25);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush22);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush23);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush24);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush25);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush26);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush25);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush25);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush22);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush22);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Highlight, brush15);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush22);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        vel_trem3->setPalette(palette4);
        vel_trem3->setMaximum(200);
        vel_trem3->setOrientation(Qt::Horizontal);
        vel_trem5 = new QSlider(centralWidget);
        vel_trem5->setObjectName(QStringLiteral("vel_trem5"));
        vel_trem5->setEnabled(true);
        vel_trem5->setGeometry(QRect(100, 440, 160, 16));
        vel_trem5->setMinimumSize(QSize(160, 16));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush28(QColor(117, 80, 123, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush28);
        QBrush brush29(QColor(176, 120, 185, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush29);
        QBrush brush30(QColor(146, 100, 154, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush30);
        QBrush brush31(QColor(58, 40, 61, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush31);
        QBrush brush32(QColor(78, 53, 82, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush32);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush28);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush31);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush28);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush29);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush30);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush31);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush32);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush28);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush31);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush31);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush28);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush29);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush30);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush31);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush32);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush31);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush31);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush28);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush28);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush28);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        vel_trem5->setPalette(palette5);
        vel_trem5->setMaximum(200);
        vel_trem5->setSliderPosition(0);
        vel_trem5->setOrientation(Qt::Horizontal);
        vel_trem4 = new QSlider(centralWidget);
        vel_trem4->setObjectName(QStringLiteral("vel_trem4"));
        vel_trem4->setGeometry(QRect(100, 420, 160, 16));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush33(QColor(237, 212, 0, 255));
        brush33.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush33);
        QBrush brush34(QColor(255, 239, 100, 255));
        brush34.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush34);
        QBrush brush35(QColor(246, 225, 50, 255));
        brush35.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush35);
        QBrush brush36(QColor(118, 106, 0, 255));
        brush36.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush36);
        QBrush brush37(QColor(158, 141, 0, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush37);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush33);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush);
        QBrush brush38(QColor(246, 233, 127, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush38);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush33);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush34);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush35);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush36);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush37);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush33);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush38);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush36);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush33);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush34);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush35);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush36);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush37);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush36);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush36);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush33);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush33);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush15);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush33);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        vel_trem4->setPalette(palette6);
        vel_trem4->setMaximum(200);
        vel_trem4->setOrientation(Qt::Horizontal);
        label_trilho3_4 = new QLabel(centralWidget);
        label_trilho3_4->setObjectName(QStringLiteral("label_trilho3_4"));
        label_trilho3_4->setGeometry(QRect(870, 30, 21, 137));
        label_trilho3_4->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho2_3 = new QLabel(centralWidget);
        label_trilho2_3->setObjectName(QStringLiteral("label_trilho2_3"));
        label_trilho2_3->setGeometry(QRect(620, 150, 250, 17));
        label_trilho2_3->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho1_3 = new QLabel(centralWidget);
        label_trilho1_3->setObjectName(QStringLiteral("label_trilho1_3"));
        label_trilho1_3->setGeometry(QRect(620, 30, 250, 17));
        label_trilho1_3->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho2_4 = new QLabel(centralWidget);
        label_trilho2_4->setObjectName(QStringLiteral("label_trilho2_4"));
        label_trilho2_4->setGeometry(QRect(210, 270, 250, 17));
        label_trilho2_4->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho3_6 = new QLabel(centralWidget);
        label_trilho3_6->setObjectName(QStringLiteral("label_trilho3_6"));
        label_trilho3_6->setGeometry(QRect(460, 150, 21, 137));
        label_trilho3_6->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho3_7 = new QLabel(centralWidget);
        label_trilho3_7->setObjectName(QStringLiteral("label_trilho3_7"));
        label_trilho3_7->setGeometry(QRect(730, 150, 21, 137));
        label_trilho3_7->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho4_4 = new QLabel(centralWidget);
        label_trilho4_4->setObjectName(QStringLiteral("label_trilho4_4"));
        label_trilho4_4->setGeometry(QRect(190, 150, 21, 137));
        label_trilho4_4->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trilho2_5 = new QLabel(centralWidget);
        label_trilho2_5->setObjectName(QStringLiteral("label_trilho2_5"));
        label_trilho2_5->setGeometry(QRect(480, 270, 250, 17));
        label_trilho2_5->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        label_trem3 = new QLabel(centralWidget);
        label_trem3->setObjectName(QStringLiteral("label_trem3"));
        label_trem3->setGeometry(QRect(600, 30, 21, 17));
        label_trem3->setStyleSheet(QStringLiteral("QLabel { background: orange}"));
        label_trem4 = new QLabel(centralWidget);
        label_trem4->setObjectName(QStringLiteral("label_trem4"));
        label_trem4->setGeometry(QRect(190, 150, 21, 17));
        label_trem4->setStyleSheet(QStringLiteral("QLabel { background: yellow}"));
        label_trem5 = new QLabel(centralWidget);
        label_trem5->setObjectName(QStringLiteral("label_trem5"));
        label_trem5->setGeometry(QRect(460, 150, 21, 17));
        QPalette palette7;
        QBrush brush39(QColor(128, 0, 128, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush39);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        label_trem5->setPalette(palette7);
        label_trem5->setStyleSheet(QStringLiteral("QLabel { background: purple}"));
        legend1 = new QLabel(centralWidget);
        legend1->setObjectName(QStringLiteral("legend1"));
        legend1->setGeometry(QRect(10, 360, 21, 17));
        legend2 = new QLabel(centralWidget);
        legend2->setObjectName(QStringLiteral("legend2"));
        legend2->setGeometry(QRect(10, 380, 21, 17));
        legend3 = new QLabel(centralWidget);
        legend3->setObjectName(QStringLiteral("legend3"));
        legend3->setGeometry(QRect(10, 440, 21, 17));
        legend4 = new QLabel(centralWidget);
        legend4->setObjectName(QStringLiteral("legend4"));
        legend4->setGeometry(QRect(10, 400, 21, 17));
        legend5 = new QLabel(centralWidget);
        legend5->setObjectName(QStringLiteral("legend5"));
        legend5->setGeometry(QRect(10, 420, 21, 17));
        label_trilho4_6 = new QLabel(centralWidget);
        label_trilho4_6->setObjectName(QStringLiteral("label_trilho4_6"));
        label_trilho4_6->setGeometry(QRect(0, 350, 331, 111));
        label_trilho4_6->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_1 = new QLabel(centralWidget);
        ponto_critico_1->setObjectName(QStringLiteral("ponto_critico_1"));
        ponto_critico_1->setGeometry(QRect(310, 80, 21, 31));
        ponto_critico_1->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_2 = new QLabel(centralWidget);
        ponto_critico_2->setObjectName(QStringLiteral("ponto_critico_2"));
        ponto_critico_2->setGeometry(QRect(580, 80, 21, 31));
        ponto_critico_2->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_3 = new QLabel(centralWidget);
        ponto_critico_3->setObjectName(QStringLiteral("ponto_critico_3"));
        ponto_critico_3->setGeometry(QRect(260, 160, 21, 31));
        ponto_critico_3->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_4 = new QLabel(centralWidget);
        ponto_critico_4->setObjectName(QStringLiteral("ponto_critico_4"));
        ponto_critico_4->setGeometry(QRect(390, 160, 21, 31));
        ponto_critico_4->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_6 = new QLabel(centralWidget);
        ponto_critico_6->setObjectName(QStringLiteral("ponto_critico_6"));
        ponto_critico_6->setGeometry(QRect(670, 160, 21, 31));
        ponto_critico_6->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_5 = new QLabel(centralWidget);
        ponto_critico_5->setObjectName(QStringLiteral("ponto_critico_5"));
        ponto_critico_5->setGeometry(QRect(550, 160, 21, 31));
        ponto_critico_5->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        ponto_critico_7 = new QLabel(centralWidget);
        ponto_critico_7->setObjectName(QStringLiteral("ponto_critico_7"));
        ponto_critico_7->setGeometry(QRect(440, 200, 21, 31));
        ponto_critico_7->setStyleSheet(QStringLiteral("QLabel { background: gray}"));
        MainWindow->setCentralWidget(centralWidget);
        ponto_critico_3->raise();
        ponto_critico_4->raise();
        ponto_critico_7->raise();
        ponto_critico_1->raise();
        ponto_critico_2->raise();
        ponto_critico_5->raise();
        ponto_critico_6->raise();
        label_trilho4_6->raise();
        label_trilho3_7->raise();
        label_trilho3_6->raise();
        label_trilho4_4->raise();
        label_trilho1->raise();
        label_trilho2->raise();
        label_trilho3->raise();
        label_trilho4->raise();
        label_trem1->raise();
        label_trilho3_5->raise();
        label_trilho1_2->raise();
        label_trilho2_2->raise();
        label_trem2->raise();
        vel_trem1->raise();
        vel_trem2->raise();
        vel_trem3->raise();
        vel_trem5->raise();
        vel_trem4->raise();
        label_trilho3_4->raise();
        label_trilho2_3->raise();
        label_trilho1_3->raise();
        label_trilho2_4->raise();
        label_trilho2_5->raise();
        label_trem3->raise();
        label_trem4->raise();
        label_trem5->raise();
        legend1->raise();
        legend2->raise();
        legend3->raise();
        legend4->raise();
        legend5->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1068, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label_trem1->setText(QApplication::translate("MainWindow", "T1", Q_NULLPTR));
        label_trilho1->setText(QString());
        label_trilho2->setText(QString());
        label_trilho3->setText(QString());
        label_trilho4->setText(QString());
        label_trilho3_5->setText(QString());
        label_trilho1_2->setText(QString());
        label_trilho2_2->setText(QString());
        label_trem2->setText(QApplication::translate("MainWindow", "T2", Q_NULLPTR));
        label_trilho3_4->setText(QString());
        label_trilho2_3->setText(QString());
        label_trilho1_3->setText(QString());
        label_trilho2_4->setText(QString());
        label_trilho3_6->setText(QString());
        label_trilho3_7->setText(QString());
        label_trilho4_4->setText(QString());
        label_trilho2_5->setText(QString());
        label_trem3->setText(QApplication::translate("MainWindow", "<html><head/><body><p>T3</p></body></html>", Q_NULLPTR));
        label_trem4->setText(QApplication::translate("MainWindow", "T4", Q_NULLPTR));
        label_trem5->setText(QApplication::translate("MainWindow", "T5", Q_NULLPTR));
        legend1->setText(QApplication::translate("MainWindow", "T1:", Q_NULLPTR));
        legend2->setText(QApplication::translate("MainWindow", "T2:", Q_NULLPTR));
        legend3->setText(QApplication::translate("MainWindow", "T5:", Q_NULLPTR));
        legend4->setText(QApplication::translate("MainWindow", "T3:", Q_NULLPTR));
        legend5->setText(QApplication::translate("MainWindow", "T4:", Q_NULLPTR));
        label_trilho4_6->setText(QString());
        ponto_critico_1->setText(QApplication::translate("MainWindow", " 1", Q_NULLPTR));
        ponto_critico_2->setText(QApplication::translate("MainWindow", " 2", Q_NULLPTR));
        ponto_critico_3->setText(QApplication::translate("MainWindow", " 3", Q_NULLPTR));
        ponto_critico_4->setText(QApplication::translate("MainWindow", " 4", Q_NULLPTR));
        ponto_critico_6->setText(QApplication::translate("MainWindow", " 6", Q_NULLPTR));
        ponto_critico_5->setText(QApplication::translate("MainWindow", " 5", Q_NULLPTR));
        ponto_critico_7->setText(QApplication::translate("MainWindow", " 7", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
